### ISSUE TITLE
exception on no $HOME/.gdcmdtools.creds

### ISSUE THREAD

**Issue by acumon** [timchen86/gdcmdtools#42]
version: latest (0.92)
when I run python ./gdauth.py client_secret.json. the python script throws an exception

Traceback (most recent call last):
  File "./gdauth.py", line 76, in <module>
    auth = GDAuth(args.secret_file, if_oob)
  File "/usr/local/google/home/xiaomingc/lab/gdcmdtools/gdcmdtools/gdcmdtools/auth.py", line 37, in __init__
    os.remove(storage_file)
OSError: [Errno 2] No such file or directory: 'MY_HOME_DIR/.gdcmdtools.creds'

**Comment by joestump** [comment]
`touch $HOME/.gdcmdtools.creds` will fix this error. It should only attempt to delete the file if it exists.

**Comment by tienfuc** [comment]
Sorry for taking it so long, the issue is fixed.
